@URL=http://localhost:3000/sensors

### CRIAR SENSORDATA ### OBS: Precisa colocar que é JSON
POST {{URL}}
Content-Type: application/json

{
    "sensorId": "2",
    "dataValue": "10"
}

### --------------------------------------------- ###

### Obter todos as SensorDatas (Sem validação)
GET {{URL}}
Content-Type: application/json

### Obter todos as SensorDatas (Com validação)
GET {{URL}}
Content-Type: application/json
Authorization: 1234

### OBTER SENSORDATAS POR ID (Com validação) ###
GET {{URL}}/68efe62528b78f864288e92e
Content-Type: application/json
Authorization: 1234

### --------------------------------------------- ###

### DELETAR SENSORDATAS POR ID (Com validação) ###
DELETE {{URL}}/68efe62528b78f864288e92e
Content-Type: application/json
Authorization: 1234

### --------------------------------------------- ###

### ATUALIZAR SENSORDATAS POR ID (Com validação) ###
UPDATE {{URL}}/68efe6b228b78f864288e937
Content-Type: application/json
Authorization: 1234

